import { Metadata } from 'next'
import { LegalPage } from '@/components/marketing/LegalPage'
export const metadata: Metadata = { title: 'Billing & Subscription Terms — FlowSync PM' }
export default function BillingTerms() {
  return <LegalPage title="Billing & Subscription Terms" lastUpdated="July 17, 2026" sections={[
    { title:"1. Overview", content:"These Billing & Subscription Terms ('Billing Terms') govern payment for FlowSync PM and form part of the Terms of Service. By starting a trial or purchasing a subscription you agree to these Billing Terms. Where these Billing Terms conflict with the Terms of Service on billing matters, these Billing Terms control." },
    { title:"2. Plans and Pricing", content:"FlowSync PM offers the following plans: Trial (free for two months); Starter at US $19 per user per month; Business at US $39 per user per month for paid-role users plus US $20 per month for each bundle of up to 10 contributor/viewer users; and Enterprise under a separately negotiated agreement. Annual billing receives a 20% discount and is charged once per year in advance. All prices are in U.S. dollars and exclude applicable taxes unless stated otherwise at checkout." },
    { title:"3. Paid Seats and Contributor Bundles (Business plan)", content:"On the Business plan, a 'paid seat' is required for users holding work-driving or governance roles: Executive Sponsor, Project Sponsor, PMO Director, Program Manager, PMO Analyst, Project Manager, and Product Owner. All other users — including Steering Committee members, Business Analysts, Technical Leads, Scrum Masters, Team Members, Stakeholders, External Resources, and Clients — are covered by contributor bundles of up to 10 users each. You are responsible for maintaining enough paid seats and bundles to cover your workspace membership; we may review usage and require an adjustment at the next billing cycle." },
    { title:"4. Free Trial and Subscribing During It — IMPORTANT", content:"New workspaces receive a two-month free trial of the full product. NO PAYMENT METHOD IS REQUIRED TO START A TRIAL, AND NO CHARGE OCCURS UNLESS YOU SUBSCRIBE. If you subscribe during the trial, your payment method is collected at checkout but IS NOT CHARGED UNTIL THE TRIAL ENDS; the exact date is shown at checkout and in Settings → Billing. FROM THAT DATE YOUR SUBSCRIPTION IS CHARGED ON A RECURRING BASIS UNTIL CANCELLED (see Section 5). You may cancel before the trial ends in Settings → Billing (Manage billing) and you will not be charged. If the trial ends without a subscription, no charges occur; workspace access is limited until a subscription begins, and your data is retained per the Terms of Service." },
    { title:"5. Automatic Renewal", content:"All paid subscriptions renew automatically at the end of each billing period (monthly or annual) until cancelled. The renewal charge is made to your payment method on file at the then-current price for your plan and quantities. You authorize FlowSync PM and its payment processor to charge your payment method on a recurring basis." },
    { title:"6. Payment Processing", content:"Payments are processed by Stripe, Inc. FlowSync PM does not store full card numbers; card details are held by Stripe under their security and PCI-DSS obligations. By subscribing you also agree to Stripe's applicable terms. Invoices and receipts are available from the billing portal in Settings → Billing." },
    { title:"7. Seat and Bundle Changes; Proration", content:"Adding paid seats or bundles mid-cycle takes effect immediately and is prorated for the remainder of the billing period. Reducing seats or bundles takes effect at the start of the next billing period; no credits are issued for mid-period reductions. Annual plans are adjusted at the same proration rules applied against the annual price." },
    { title:"8. Cancellation", content:"You may cancel at any time in Settings → Billing (Manage billing) or by written notice to support. Cancellation takes effect at the end of the current billing period; you retain access until then. After cancellation your workspace reverts to read-only access for 30 days, during which you may export your data, after which data is handled per the Terms of Service and Privacy Policy retention rules." },
    { title:"9. Refunds", content:"Except where required by applicable law, payments are non-refundable and no refunds or credits are provided for partial billing periods, unused seats, or unused bundles. If you believe a charge was made in error, contact support within 30 days of the charge and we will review it in good faith." },
    { title:"10. Failed Payments", content:"If a renewal charge fails, we will retry it and notify you. If payment remains unsuccessful after reasonable retries over a period of up to 14 days, we may downgrade or suspend the workspace until payment is brought current. We will not delete your data solely due to a failed payment during that period." },
    { title:"11. Price Changes", content:"We may change prices with at least 30 days' notice by email and in-product. Price changes take effect at your next renewal after the notice period. If you do not agree to a price change, you may cancel before it takes effect. Prices locked by a written Enterprise agreement follow that agreement." },
    { title:"12. Taxes", content:"Prices exclude sales tax, VAT, IVU, and similar taxes unless stated otherwise at checkout. Where we are required to collect taxes, they are added at checkout or on the invoice based on your billing address. You are responsible for any taxes not collected by us that apply to your purchase." },
    { title:"13. Enterprise Agreements", content:"Enterprise subscriptions are governed by a separately executed order form or agreement covering pricing, seat counts, payment terms (including invoicing), and any custom terms such as a Data Processing Agreement or SLA. Where an Enterprise agreement exists, it prevails over these Billing Terms to the extent of any conflict." },
    { title:"14. Changes to These Terms", content:"We may update these Billing Terms from time to time. Material changes will be notified by email or in-product at least 30 days before taking effect. Continued use of a paid subscription after the effective date constitutes acceptance." },
    { title:"15. Contact", content:"Billing questions: open Settings → Billing → Contact us, or email the address shown on your invoice. We aim to answer billing questions within one business day." },
  ]} />
}
