import { Metadata } from 'next'
import { LegalPage } from '@/components/marketing/LegalPage'
export const metadata: Metadata = { title: 'Terms of Service — FlowSync PM' }
export default function Terms() {
  return <LegalPage title="Terms of Service" lastUpdated="July 1, 2026" sections={[
    { title:"1. Acceptance of Terms", content:"By accessing or using FlowSync PM ('the Service'), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These Terms apply to all users, including workspace owners, administrators, team members, and clients." },
    { title:"2. Description of Service", content:"FlowSync PM is a cloud-based project management platform designed for project management offices (PMOs) and project teams. Features include task management, risk tracking, Earned Value Management (EVM), PM Standard-aligned governance workflows, and AI-assisted reporting. The platform is industry-neutral and serves organizations of all sizes." },
    { title:"3. Account Registration", content:"You must provide accurate, complete information when creating an account. You are responsible for maintaining the confidentiality of your credentials. You must notify us immediately of any unauthorized access. You may not use another person's account without permission." },
    { title:"4. Subscription Plans and Billing", content:"FlowSync PM offers a two-month free Trial, Starter (US $19/user/mo), Business (US $39/user/mo for paid-role users plus US $20/mo per bundle of up to 10 contributor users), and Enterprise (custom agreement) plans. Annual billing receives a 20% discount. No payment method is required to start the Trial; subscriptions purchased during the Trial are first charged when the Trial ends and renew automatically thereafter. Full payment, renewal, cancellation, and refund terms — including the automatic-renewal and trial-conversion disclosures — are set out in the Billing & Subscription Terms at /legal/billing, which form part of these Terms." },
    { title:"5. Acceptable Use", content:"You may not use FlowSync PM to: (a) violate any applicable law or regulation; (b) transmit harmful, threatening, or illegal content; (c) attempt to gain unauthorized access to other accounts or systems; (d) use automated tools to scrape or extract data beyond normal API usage; (e) resell access to the Service without authorization; (f) upload malware or malicious code." },
    { title:"6. Data Ownership", content:"You retain ownership of all data, content, and files you upload to FlowSync PM. By uploading content, you grant FlowSync PM a limited, non-exclusive license to store, process, and display your content solely for the purpose of providing the Service. We do not sell your data to third parties." },
    { title:"7. AI-Generated Content", content:"FlowSync PM includes AI-powered features including report generation and content analysis. AI-generated outputs are drafts for human review and are not professional advice of any kind, including legal or financial advice. Users are responsible for reviewing and validating all AI-generated content before distribution or use in decision-making." },
    { title:"8. Intellectual Property", content:"FlowSync PM and its original content, features, and functionality are owned by FlowSync PM and are protected by international copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works of the platform without written permission." },
    { title:"9. Termination", content:"We may terminate or suspend your account at any time for violation of these Terms. You may delete your account at any time. Upon termination, your right to use the Service ceases immediately. We will retain your data for 30 days after termination to allow data export, after which it will be deleted." },
    { title:"10. Limitation of Liability", content:"TO THE MAXIMUM EXTENT PERMITTED BY LAW, FLOWSYNC PM SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL. IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE AMOUNT PAID BY YOU IN THE TWELVE MONTHS PRECEDING THE CLAIM." },
    { title:"11. Governing Law", content:"These Terms are governed by the laws of the Commonwealth of Puerto Rico and the United States of America. Any disputes shall be resolved in the courts of Puerto Rico, and you consent to personal jurisdiction therein." },
    { title:"12. Changes to Terms", content:"We may update these Terms at any time. We will notify you of material changes via email or in-app notification at least 30 days before they take effect. Continued use after changes constitutes acceptance." },
    { title:"13. Contact", content:"For questions about these Terms, contact legal@flowsyncpm.com." },
  ]} />
}
