import { Metadata } from 'next'
import { LegalPage } from '@/components/marketing/LegalPage'
export const metadata: Metadata = { title: 'Terms of Service — FlowSync PM' }
export default function Terms() {
  return <LegalPage title="Terms of Service" lastUpdated="July 21, 2026" sections={[
    { title:"1. Acceptance of Terms", content:"By accessing or using FlowSync PM ('the Service'), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These Terms apply to all users, including workspace owners, administrators, team members, and clients. If you register or use the Service with an email address belonging to an employer or other entity, or act as a workspace administrator, you represent that you have authority to bind that entity, and these Terms bind it. The Service is operated by Flow Sync PM, a registered merchant in the Commonwealth of Puerto Rico (Merchant Registration No. 1552654-0010, NAICS 54151)." },
    { title:"2. Description of Service", content:"FlowSync PM is a cloud-based project management platform designed for project management offices (PMOs) and project teams. Features include task management, risk tracking, Earned Value Management (EVM), PM Standard-aligned governance workflows, and AI-assisted reporting. The platform is industry-neutral and serves organizations of all sizes." },
    { title:"3. Account Registration", content:"You must provide accurate, complete information when creating an account. You are responsible for maintaining the confidentiality of your credentials. You must notify us immediately of any unauthorized access. You may not use another person's account without permission." },
    { title:"4. Workspace Administrators and Users", content:"Each workspace has one or more administrators designated by the customer. Administrators are the customer's authorized representatives: they control user access and roles, purchase or change plans, and manage workspace data, and their actions are deemed actions of the customer. The customer is responsible for its users' compliance with these Terms and for assigning appropriate roles. Personal data and activity within a workspace may be visible to and managed by that workspace's administrators." },
    { title:"5. Subscription Plans and Billing", content:"FlowSync PM offers a two-month free Trial, Starter (US $19/user/mo), Business (US $39/user/mo for paid-role users plus US $20/mo per bundle of up to 10 contributor users), and Enterprise (custom agreement) plans. Annual billing receives a 20% discount. No payment method is required to start the Trial; subscriptions purchased during the Trial are first charged when the Trial ends and renew automatically thereafter. Full payment, renewal, cancellation, and refund terms — including the automatic-renewal and trial-conversion disclosures — are set out in the Billing & Subscription Terms at /legal/billing, which form part of these Terms." },
    { title:"6. Acceptable Use", content:"You may not use FlowSync PM to: (a) violate any applicable law or regulation; (b) transmit harmful, threatening, or illegal content; (c) attempt to gain unauthorized access to other accounts or systems; (d) use automated tools to scrape or extract data beyond normal API usage; (e) resell access to the Service without authorization; (f) upload malware or malicious code." },
    { title:"7. Sensitive Data Restrictions", content:"The Service is a project management platform and is not designed or offered for the storage or processing of specially regulated data. You must not submit to the Service: (a) Protected Health Information (PHI) as defined under HIPAA, unless your organization has an Enterprise agreement and a separately executed HIPAA Business Associate Agreement with us — absent that executed agreement, no HIPAA obligations exist and PHI must not be uploaded; (b) payment card data subject to PCI DSS (payments to us are processed by Stripe; never enter card numbers into project records); or (c) special categories of personal data under GDPR Article 9 or equivalent laws, except where you have established a lawful basis and such data is strictly necessary to the project record. We may remove data submitted in violation of this section and are not liable for it." },
    { title:"8. Data Ownership", content:"You retain ownership of all data, content, and files you upload to FlowSync PM. By uploading content, you grant FlowSync PM a limited, non-exclusive license to store, process, and display your content solely for the purpose of providing the Service. We do not sell your data to third parties." },
    { title:"9. AI-Generated Content", content:"FlowSync PM includes AI-powered features including report generation and content analysis. AI-generated outputs are drafts for human review and are not professional advice of any kind, including legal or financial advice. Users are responsible for reviewing and validating all AI-generated content before distribution or use in decision-making." },
    { title:"10. Third-Party Services and Integrations", content:"The Service can connect to third-party services you choose to enable, such as Microsoft 365 (Outlook, Calendar, Teams, Planner), Google sign-in, and services you connect via webhooks or the API. Your use of a third-party service is governed by that provider's own terms and privacy policy, not these Terms, and data you authorize to flow between the Service and a third-party service is processed by that provider under its policies. You may disconnect integrations at any time (for Microsoft, also from your Microsoft account). We are not responsible for third-party services' availability, security, or data practices, and integrations are provided on an as-available basis." },
    { title:"11. Intellectual Property", content:"FlowSync PM and its original content, features, and functionality are owned by FlowSync PM and are protected by international copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works of the platform without written permission. If you submit suggestions or feedback about the Service, we may use them without restriction or obligation." },
    { title:"12. Termination", content:"We may terminate or suspend your account at any time for violation of these Terms. You may delete your account at any time. Upon termination, your right to use the Service ceases immediately. We will retain your data for 30 days after termination to allow data export, after which it will be deleted." },
    { title:"13. Warranty Disclaimer", content:"EXCEPT AS EXPRESSLY STATED IN THESE TERMS, THE SERVICE IS PROVIDED 'AS IS' AND 'AS AVAILABLE', WITHOUT WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT DATA WILL NOT BE LOST — MAINTAIN YOUR OWN EXPORTS OF CRITICAL DATA. AI-GENERATED OUTPUTS ARE DRAFTS FOR HUMAN REVIEW AND ARE NOT WARRANTED TO BE ACCURATE OR COMPLETE." },
    { title:"14. Limitation of Liability", content:"TO THE MAXIMUM EXTENT PERMITTED BY LAW, FLOWSYNC PM SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL. IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE AMOUNT PAID BY YOU IN THE TWELVE MONTHS PRECEDING THE CLAIM." },
    { title:"15. Indemnification", content:"You agree to defend and indemnify FlowSync PM against third-party claims arising from (a) your or your users' violation of these Terms or applicable law, or (b) your customer data, including claims that it infringes or violates a third party's rights. We will defend you against third-party claims that your authorized use of the Service infringes a U.S. copyright or trademark, and pay damages finally awarded, provided you promptly notify us and grant control of the defense; this states our entire liability for intellectual-property claims regarding the Service." },
    { title:"16. Governing Law", content:"These Terms are governed by the laws of the Commonwealth of Puerto Rico and the United States of America. Any disputes shall be resolved in the courts of Puerto Rico, and you consent to personal jurisdiction therein." },
    { title:"17. Changes to Terms", content:"We may update these Terms at any time. We will notify you of material changes via email or in-app notification at least 30 days before they take effect. Continued use after changes constitutes acceptance." },
    { title:"18. Contact", content:"For questions about these Terms, contact legal@flowsyncpm.com." },
  ]} />
}
